# This file includes the minimum code required to build and test a site with ProboCI.
# All other code is stored in SU-SWS/proboci_assets and should be updated there.

steps:
  - name: Run tests from proboci_assets repository
    command: "git clone https://github.com/SU-SWS/proboci_assets.git /srv/proboci_assets; /srv/probo.sh"

