# This file includes the minimum code required to build and test a site with ProboCI.
# All other code is stored in SU-SWS/proboci_assets and should be updated there.
# Best methods for managing keys is still up for discussion.

# Uncomment if building a product other than a self-service site.
assets:
 - proboci_id_rsa
 - proboci_id_rsa.pub

# Uncomment and place between downloading the proboci_assets repository and running the probo.sh script.
# Add which product you would like to build by running the script with the name of the profile,
# ie. /srv/proboci_assets/probo.sh jumpstart-academic
# Choices include stanford, jumpstart, jumpstart-academic, jumpstart-engineering
# And jumpstart-plus

steps:
  - name: Run tests from external proboci_assets repository
    command: "git clone https://github.com/SU-SWS/proboci_assets.git /srv/proboci_assets;
      cp $ASSET_DIR/proboci_id_rsa.pub /root/.ssh/id_rsa.pub;
      cp $ASSET_DIR/proboci_id_rsa /root/.ssh/id_rsa;
      /srv/proboci_assets/probo.sh stanford"
