assets:
  - ngrok.yml
  - .shoov.json
  - .shoov.yml
  - proboci_id_rsa
  - proboci_id_rsa.pub
steps:
  - name: Download Drupal Behat and Shoov
    plugin: Script
    script: |
      cp $ASSET_DIR/proboci_id_rsa /root/.ssh/id_rsa
      cp $ASSET_DIR/proboci_id_rsa.pub /root/.ssh/id_rsa.pub
      git clone git@github.com:SU-SWS/stanford_sites_jumpstart_academic.git /srv/stanford_sites_jumpstart_academic
      service mysql start
      echo 'export PATH="/usr/bin/mysql:$PATH"' >> /root/.bash_profile
      source /root/.bash_profile
      mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('root')";
      echo 'Download Probo CI assets'
      git clone https://github.com/SU-SWS/proboci_assets.git /srv/proboci_assets
      echo 'Install ngrok'
      wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O /srv/ngrok.zip
      unzip /srv/ngrok.zip -d /srv
      cp $ASSET_DIR/ngrok.yml /srv/ngrok.yml
      (wget -O - pi.dk/3 || curl pi.dk/3/ || fetch -o - http://pi.dk/3) | bash
      echo 'Install node modules'
      npm install -g npm
      npm install -g grunt-cli mocha gm webdrivercss webdriverio selenium-standalone chromedriver
      echo 'Install Geppetto'
      git clone https://github.com/SU-SWS/stanford_geppetto.git /srv/stanford_geppetto
      cd /srv/stanford_geppetto
      git checkout proboci
      npm install
      cp /srv/proboci_assets/configure.json /srv/stanford_geppetto/configure.json
      echo 'Build site'
      cd /srv/stanford_geppetto
      grunt build:make:install --build-product=jumpstart-academic --build-database-name=html
      echo 'Enable relevant modules'
      mkdir -p /var/www/html/sites/all/modules/stanford/stanford_bean_types
      chown -R www-data:www-data /var/www/html/sites/default/files
      cd /var/www/html
      drush dl features ds bean
      drush en -y features bean_admin_ui ds_extras
      drush fra -y
      drush dis overlay -y
      drush updb -y
      drush cc all -y
      echo 'Download behat tests and start selenium server'
      git clone https://github.com/SU-SWS/linky_clicky.git /srv/linky_clicky
      cd /srv/linky_clicky
      composer install
      selenium-standalone install
      git checkout shoov
      cp /srv/proboci_assets/behat.local.yml /srv/linky_clicky/sites/probo/behat.local.yml
      echo 'Download shoov tests'
      cp $ASSET_DIR/.shoov.json /root/.shoov.json
      mkdir -p /srv/linky_clicky/sites/probo/visual-monitor/test
      cp /srv/proboci_assets/package.json /srv/linky_clicky/sites/probo/package.json
      cd /srv/linky_clicky/sites/probo
      npm install
      cp /srv/proboci_assets/.shoov.yml /srv/linky_clicky/sites/probo/.shoov.yml
      mkdir /srv/linky_clicky/sites/probo/visual-monitor/webdrivercss
      echo 'Setting 127.0.0.1 to html after loading database' 
      echo "127.0.0.1 html" >> /etc/hosts
  - name: Copy relevant tests
    script: |
      cp /srv/linky_clicky/includes/features/SU-SWS/stanford_bean_types/stanford_bean_types.feature /srv/linky_clicky/sites/probo/features/.
      cp /srv/proboci_assets/tests.js /srv/linky_clicky/sites/probo/visual-monitor/test/tests.js
      sed -i -e 's/PROBO_BUILD_DOMAIN/$BUILD_DOMAIN/' /srv/linky_clicky/sites/probo/visual-monitor/test/tests.js
  - name: Run relevant Behat tests
    script: |
      nohup selenium-standalone start &>/dev/null &
      cd /srv/linky_clicky/sites/probo
      /srv/linky_clicky/bin/behat features/stanford_bean_types.feature --profile default --suite dev
  - name: Run relevant Shoov tests
    command: "cd /srv/linky_clicky/sites/probo/visual-monitor; parallel ::: 'timeout 30s /srv/ngrok start -config /srv/ngrok.yml html' 'PROVIDER_PREFIX=browserstack SELECTED_CAPS=chrome mocha'"
